name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: pe-arc-runner-shared-npd

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: stone-botany-426817-p5

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: cd GCP-GHA && terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }} 

      - name: 'Terraform Plan'
        run: cd GCP-GHA && terraform plan -var-file environments/layers/npd/env.tfvars
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }} 

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        run: cd GCP-GHA && terraform apply -auto-approve -var-file environments/layers/npd/env.tfvars
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
